
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientThemeProvider from "@/app/components/ClientThemeProvider";
import PrimarySearchAppBar from "@/app/components/PrimarySearchAppBar";
import { getUserIdFromRequest } from "@/app/lib/getUserId"; // Our 
import "./globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //this will help in importing the users Id to be used further
  const userId = await getUserIdFromRequest();


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ClientThemeProvider>
          <PrimarySearchAppBar userId={userId} />
         
          <main>{children}</main>
        </ClientThemeProvider>
      </body>
    </html>
  );
}



