
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientThemeProvider from "@/app/components/ClientThemeProvider";
import PrimarySearchAppBar from "@/app/components/PrimarySearchAppBar";
import { getUserIdFromRequest } from "@/app/lib/getUserId"; // Our 
import "./globals.css";
import { getUserDetails } from "./actions";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //this will help in importing the users Id to be used further
  const userId = await getUserIdFromRequest();

 console.log(userId, "userId from layout");
// Fetch the full user data using the userId

const user = await getUserDetails(userId);
  console.log(user, "user from layout");
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ClientThemeProvider>
          <PrimarySearchAppBar userId={user} />
         
          <main>
            {children}
            <Toaster position="bottom-right" reverseOrder={false} />
            </main>
        </ClientThemeProvider>
      </body>
    </html>
  );
}



