

import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientThemeProvider from "@/app/components/ClientThemeProvider";
import PrimarySearchAppBar from "@/app/components/PrimarySearchAppBar";
import { getUserIdFromRequest } from "@/app/lib/getUserId"; 
import { getUserDetails } from "./actions";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const userId = await getUserIdFromRequest();

 const user = userId ? await getUserDetails(userId) : null;
  

  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientThemeProvider>
          <PrimarySearchAppBar userId={user} />
          <main>
            {children}
            {/* <Toaster position="bottom-right" reverseOrder={false} /> */}
          </main>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
